using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;

namespace OutlookAddInTest
{
	class JsonGetter
	{
		public static JObject getJsonObject()
		{
			return JObject.Parse(@"
			{
				""jagged"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged1"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""Josh"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagge2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""Noah"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged3"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""Alex"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged4"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""New Name"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged5"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""Old Name"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagge6"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""Searching"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged7"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""Other"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged8"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""Jason"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged9"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged10"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged11"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged12"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged13"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged14"":
					{
						""id"":""value2"",
						""type"":""Contact"",
						""name"":""Jason"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged15"":
					{
						""id"":""value2"",
						""type"":""Contact"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged16"":
					{
						""id"":""value2"",
						""type"":""Contact"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged17"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged18"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged19"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged20"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged21"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged22"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged2"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					},
				""jagged3"":
					{
						""id"":""value2"",
						""type"":""Account"",
						""name"":""NPCA"",
						""email"":""millerna@rose-hulman.edu"",
						""info"":""test""
					}
			}");
		}

	}

	public class Result
	{
		public int id { get; set; }
		public String type { get; set; }
		public String name {get; set; }
		public string email { get; set; }
		public string info { get; set; }
	}
}
